spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    platform: postgres
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWD}
    driverClassName: org.postgresql.Driver

url:
  movie-service: ${MOVIE_SERVICE_URL}
  user-service: ${USER_SERVICE_URL}
  user-profile-service: ${USER_PROFILE_SERVICE_URL}