spring:
  application:
    name: user-service

  profiles:
    default: local

server:
  port: 8082

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"