# Start app with:
#  java -jar your-application.jar --spring.config.additional-location=file:C:/Users/<user name>/IdeaProjects/movie-recommendation-service/secrets.yaml
spring:
  config:
    additional-location: 'file:./secrets.yaml'

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWD}
    driverClassName: org.postgresql.Driver

