spring:
  application:
    name: movie-service

  profiles:
    active: local

  datasource:
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWD}
      driverClassName: org.postgresql.Driver
  server:
    port: 8081

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"