spring:
  config:
    import: 'optional:file:./secrets.yaml'
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWD}
    driverClassName: org.postgresql.Driver
